version: '3.9'
services:
  notify:
    image: registry.rtuitlab.dev/rtuitlab/itlab-notify:${SERVICE_VERSION:-latest}
    environment:
      - ITLAB_NOTIFY_PORT=5511
      - ITLAB_NOTIFY_REDIS_HOST=${ITLAB_NOTIFY_REDIS_HOST?Provide redis host in ITLAB_NOTIFY_REDIS_HOST}
      - ITLAB_NOTIFY_REDIS_PORT=${ITLAB_NOTIFY_REDIS_PORT?Provide redis port in ITLAB_NOTIFY_REDIS_PORT}
      - ITLAB_NOTIFY_REDIS_PASSWORD=${ITLAB_NOTIFY_REDIS_PASSWORD?Provide redis password in ITLAB_NOTIFY_REDIS_PASSWORD}
      - ITLAB_NOTIFY_DB_HOST=${ITLAB_NOTIFY_DB_HOST?Provide notify postgres database host in ITLAB_NOTIFY_DB_HOST}
      - ITLAB_NOTIFY_DB_PORT=${ITLAB_NOTIFY_DB_PORT?Provide notify postgres database port in ITLAB_NOTIFY_DB_PORT}
      - ITLAB_NOTIFY_DB_NAME=${ITLAB_NOTIFY_DB_NAME?Provide notify postgres database name in ITLAB_NOTIFY_DB_NAME}
      - ITLAB_NOTIFY_DB_USER=${ITLAB_NOTIFY_DB_USER?Provide notify postgres database username in ITLAB_NOTIFY_DB_USER}
      - ITLAB_NOTIFY_DB_PASS=${ITLAB_NOTIFY_DB_PASS?Provide notify postgres database password in ITLAB_NOTIFY_DB_PASS}
      - ITLAB_NOTIFY_AUTH_TOKEN=${ITLAB_NOTIFY_AUTH_TOKEN?Provide notify get all users token from ITLab-Back ITLAB_NOTIFY_AUTH_TOKEN}
      - ITLAB_NOTIFY_PUSH_CHANNEL=${ITLAB_NOTIFY_PUSH_CHANNEL?Provide notify reids publish channel ITLAB_NOTIFY_PUSH_CHANNEL}
      - ITLAB_NOTIFY_AUTH_URL=http://proxy:5500/api/user/all
      - ITLAB_NOTIFY_AUTH_GET_QUERY=${ITLAB_NOTIFY_AUTH_GET_QUERY-}
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"